name: DavidDorn2
favicon: null
layout_spectrum: 0.28342
typography_spectrum: 0.60948
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010101'
    - '#d9d9d9'
    - '#353535'
    - '#b5b5b5'
    - '#777777'
  brandStrength: 0.37235557846724987
  lightness: 0.5706604195293039
  saturation: 0.8893731895368546
  rhythmicContrast: 0.2911160457879305
purpose: []
