name: DavidDorn2
favicon: null
layout_spectrum: 0.5479075035545975
typography_spectrum: 0.6936423175502568
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.37235557846724987
  lightness: 0.5706604195293039
  saturation: 0.8893731895368546
  rhythmicContrast: 0.2911160457879305
purpose: []
